services:
  react:
    build:
      context: .
      dockerfile: ./docker/client-app/Dockerfile
    depends_on:
      - webapi
    volumes:
      - ./docker/client-app/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/client-app/nginx/conf.d:/etc/nginx/conf.d:ro
    ports:
      - 8080:80
    networks:
      - frontend
    restart: always
  webapi:
    build:
      context: .
      dockerfile: ./docker/web-api/Dockerfile
    depends_on:
      - database
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__Postgres: Server=database;Database=postgres;Username=postgres;Password=mysecretpassword
    networks:
      - frontend
      - backend
    restart: always
  database:
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    networks:
      - backend
    restart: always
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
