openapi: 3.0.1
info:
  title: Weather forecast API
  version: v1
paths:
  /api/v1/weatherforecast:
    get:
      tags:
        - WeatherForecast
      summary: Gets whether forecast list.
      operationId: GetWeatherForecast
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WeatherForecast'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
components:
  schemas:
    ProblemDetails:
      type: object
      properties:
        type:
          type: string
          nullable: true
        title:
          type: string
          nullable: true
        status:
          type: integer
          format: int32
          nullable: true
        detail:
          type: string
          nullable: true
        instance:
          type: string
          nullable: true
      additionalProperties: { }
    WeatherForecast:
      type: object
      properties:
        date:
          type: string
          format: date-time
        temperature_c:
          type: integer
          format: int32
        temperature_f:
          type: integer
          format: int32
          readOnly: true
        summary:
          type: string
          nullable: true
      additionalProperties: false