env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - airbnb
  - airbnb-typescript
  - prettier
parserOptions:
  ecmaFeatures:
    jsx: true
  project: ./tsconfig.json
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules:
  react/react-in-jsx-scope: off
