env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - airbnb
  - airbnb-typescript
  - prettier
parserOptions:
  ecmaFeatures:
    jsx: true
  project: ./tsconfig.json
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules:
  import/no-extraneous-dependencies:
    - "error"
    - devDependencies:
        - "**/*.stories.tsx"
        - "**/*.test.ts"
        - "vite.config.ts"
      optionalDependencies: false
  import/prefer-default-export: off
  react/function-component-definition: off
  react/react-in-jsx-scope: off
